package com.accounting_system.accounting_system_backend.domain.entities.enums;

public enum PermissionCode {
    ROLE_VISUALIZATION,
    ROLE_REGISTRATION,
    USER_VISUALIZATION,
    USER_REGISTRATION,
    CLIENT_VISUALIZATION,
    CLIENT_REGISTRATION,
    VENDOR_VISUALIZATION,
    VENDOR_REGISTRATION,
    ITEM_VISUALIZATION,
    ITEM_REGISTRATION,
    ACCOUNT_VISUALIZATION,
    ACCOUNT_REGISTRATION
}
